// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import { DecoManifest } from "$live/types.ts";
import * as $0 from "./routes/[...catchall].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_middleware.ts";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/LiveControls.tsx";
import * as $$1 from "./islands/Slider.tsx";
import * as $$$0 from "./sections/AboutUs.tsx";
import * as $$$1 from "./sections/Banner.tsx";
import * as $$$2 from "./sections/Head.tsx";
import * as $$$3 from "./sections/Header.tsx";
import * as $$$4 from "./sections/MediaCarousel.tsx";
import * as $$$5 from "./sections/PartnersList.tsx";
import * as $$$6 from "./sections/PartnersSections.tsx";
import * as $$$7 from "./sections/QuillText.tsx";
import * as $$$$0 from "./functions/LoadGitHubRaw.ts";

const manifest: DecoManifest = {
  routes: {
    "./routes/[...catchall].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_middleware.ts": $2,
    "./routes/index.tsx": $3,
  },
  islands: { "./islands/LiveControls.tsx": $$0, "./islands/Slider.tsx": $$1 },
  sections: {
    "./sections/AboutUs.tsx": $$$0,
    "./sections/Banner.tsx": $$$1,
    "./sections/Head.tsx": $$$2,
    "./sections/Header.tsx": $$$3,
    "./sections/MediaCarousel.tsx": $$$4,
    "./sections/PartnersList.tsx": $$$5,
    "./sections/PartnersSections.tsx": $$$6,
    "./sections/QuillText.tsx": $$$7,
  },
  functions: { "./functions/LoadGitHubRaw.ts": $$$$0 },
  schemas: {
    "./sections/AboutUs.tsx": {
      "inputSchema": {
        "title": " About Us",
        "type": "object",
        "properties": {
          "image": {
            "format": "image-uri",
            "type": "string",
            "title": "Image",
          },
          "title": {
            "type": "string",
            "title": "Title",
          },
          "text": {
            "format": "html",
            "type": "string",
            "title": "Text",
          },
          "button": {
            "title": "Button",
            "type": "object",
            "properties": {
              "link": {
                "type": "string",
                "title": "Link",
              },
              "text": {
                "type": "string",
                "title": "Text",
              },
            },
            "required": [
              "link",
              "text",
            ],
          },
          "feedback": {
            "title": "Feedback",
            "type": "object",
            "properties": {
              "image": {
                "format": "image-uri",
                "type": "string",
                "title": "Image",
              },
              "text": {
                "type": "string",
                "title": "Text",
              },
              "name": {
                "type": "string",
                "title": "Name",
              },
            },
            "required": [
              "image",
              "text",
              "name",
            ],
          },
        },
        "required": [
          "image",
          "title",
          "text",
          "button",
          "feedback",
        ],
      },
      "outputSchema": null,
    },
    "./sections/Banner.tsx": {
      "inputSchema": {
        "title": " Banner",
        "type": "object",
        "properties": {
          "imageDesktop": {
            "format": "image-uri",
            "type": "string",
            "title": "Image Desktop",
          },
          "imageMobile": {
            "format": "image-uri",
            "type": "string",
            "title": "Image Mobile",
          },
          "title": {
            "format": "html",
            "type": "string",
            "title": "Title",
          },
          "subtitle": {
            "type": "string",
            "title": "Subtitle",
          },
          "button": {
            "title": "Button",
            "type": "object",
            "properties": {
              "text": {
                "type": "string",
                "title": "Text",
              },
              "link": {
                "type": "string",
                "title": "Link",
              },
            },
            "required": [
              "text",
              "link",
            ],
          },
        },
        "required": [
          "imageDesktop",
          "imageMobile",
          "title",
          "subtitle",
          "button",
        ],
      },
      "outputSchema": null,
    },
    "./sections/Head.tsx": {
      "inputSchema": {
        "title": " Head",
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "title": "Title",
          },
          "description": {
            "type": "string",
            "title": "Description",
          },
          "url": {
            "type": "string",
            "title": "Url",
          },
          "imageUrl": {
            "type": "string",
            "title": "Image Url",
          },
          "faviconUrl": {
            "type": "string",
            "title": "Favicon Url",
          },
          "styleUrls": {
            "type": "array",
            "items": {
              "type": "string",
            },
            "title": "Style Urls",
          },
          "themeColor": {
            "type": "string",
            "title": "Theme Color",
          },
        },
        "required": [
          "title",
          "description",
          "url",
          "imageUrl",
          "faviconUrl",
          "styleUrls",
          "themeColor",
        ],
      },
      "outputSchema": null,
    },
    "./sections/Header.tsx": {
      "inputSchema": {
        "title": " Header",
        "type": "object",
        "properties": {
          "logo": {
            "title": "Logo",
            "type": "object",
            "properties": {
              "image": {
                "format": "image-uri",
                "type": "string",
                "title": "Image",
              },
              "altText": {
                "type": "string",
                "title": "Alt Text",
              },
            },
            "required": [
              "image",
              "altText",
            ],
          },
          "menu": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "text": {
                  "type": "string",
                  "title": "Text",
                },
                "link": {
                  "type": "string",
                  "title": "Link",
                },
              },
              "required": [
                "text",
                "link",
              ],
            },
            "title": "Menu",
          },
          "button": {
            "title": "Button",
            "type": "object",
            "properties": {
              "text": {
                "type": "string",
                "title": "Text",
              },
              "link": {
                "type": "string",
                "title": "Link",
              },
            },
            "required": [
              "text",
              "link",
            ],
          },
          "social": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "image": {
                  "type": "string",
                  "title": "Image",
                },
                "link": {
                  "type": "string",
                  "title": "Link",
                },
              },
              "required": [
                "image",
                "link",
              ],
            },
            "title": "Social",
          },
        },
        "required": [
          "logo",
          "menu",
          "button",
          "social",
        ],
      },
      "outputSchema": null,
    },
    "./sections/MediaCarousel.tsx": {
      "inputSchema": {
        "title": " Media Carousel",
        "type": "object",
        "properties": {
          "media": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "image": {
                  "format": "image-uri",
                  "type": "string",
                  "title": "Image",
                },
                "link": {
                  "type": "string",
                  "title": "Link",
                },
              },
              "required": [
                "image",
                "link",
              ],
            },
            "title": "Media",
          },
          "text": {
            "type": "string",
            "title": "Text",
          },
        },
        "required": [
          "media",
          "text",
        ],
      },
      "outputSchema": null,
    },
    "./sections/PartnersList.tsx": {
      "inputSchema": {
        "title": " Partners List",
        "type": "object",
        "properties": {
          "title": {
            "format": "html",
            "type": "string",
            "title": "Title",
          },
          "company": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "image": {
                  "format": "image-uri",
                  "type": "string",
                  "title": "Image",
                },
                "altImage": {
                  "type": "string",
                  "title": "Alt Image",
                },
              },
              "required": [
                "image",
                "altImage",
              ],
            },
            "title": "Company",
          },
          "button": {
            "title": "Button",
            "type": "object",
            "properties": {
              "text": {
                "type": "string",
                "title": "Text",
              },
              "link": {
                "type": "string",
                "title": "Link",
              },
            },
            "required": [
              "text",
              "link",
            ],
          },
        },
        "required": [
          "title",
          "company",
          "button",
        ],
      },
      "outputSchema": null,
    },
    "./sections/PartnersSections.tsx": {
      "inputSchema": {
        "title": " Partners Sections",
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "title": "Title",
          },
          "text": {
            "format": "html",
            "type": "string",
            "title": "Text",
          },
          "button": {
            "title": "Button",
            "type": "object",
            "properties": {
              "text": {
                "type": "string",
                "title": "Text",
              },
              "link": {
                "type": "string",
                "title": "Link",
              },
            },
            "required": [
              "text",
              "link",
            ],
          },
          "block": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "title": {
                  "type": "string",
                  "title": "Title",
                },
                "text": {
                  "type": "string",
                  "title": "Text",
                },
              },
              "required": [
                "title",
                "text",
              ],
            },
            "title": "Block",
          },
        },
        "required": [
          "title",
          "text",
          "button",
          "block",
        ],
      },
      "outputSchema": null,
    },
    "./sections/QuillText.tsx": {
      "inputSchema": {
        "title": " Quill Text",
        "type": "object",
        "properties": {
          "html": {
            "format": "html",
            "type": "string",
            "title": "Html",
          },
        },
        "required": [
          "html",
        ],
      },
      "outputSchema": null,
    },
    "./functions/LoadGitHubRaw.ts": {
      "inputSchema": {
        "title": " Load Git Hub Raw",
        "type": "object",
        "properties": {
          "repo": {
            "type": "string",
            "title": "Repo",
            "description": "Complete user/repo format",
          },
          "branch": {
            "type": "string",
            "title": "Branch",
            "description": "Branch",
          },
          "path": {
            "type": "string",
            "title": "Path",
            "description":
              "Path to fetch, or leave blank and add :path route param.",
          },
        },
        "required": [
          "repo",
          "branch",
          "path",
        ],
      },
      "outputSchema": {
        "type": "object",
        "properties": {
          "data": {
            "$id": "5b1cd5713a375e18bb93e9635b8a2dc5fc2672cf",
          },
        },
        "additionalProperties": true,
      },
    },
  },
  baseUrl: import.meta.url,
  config,
};

// live — this exposes the manifest so the live server can render components dynamically
globalThis.manifest = manifest;

export default manifest;
